name       : snapraid
version    : '11.5'
release    : 3
source     :
    - https://github.com/amadvance/snapraid/releases/download/v11.5/snapraid-11.5.tar.gz : 1f5267261bdbcf4d48b9359ce67184df11905590739140f740327fb73bcecafa
license    : GPL-3.0-or-later
component  : system.utils
summary    : A backup program for disk arrays
description: |
    Snapraid stores parity information of your data and can recover it from up to six disk failures
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
