name       : snapraid
version    : 11.3
release    : 2
source     :
    - https://github.com/amadvance/snapraid/releases/download/v11.3/snapraid-11.3.tar.gz : d35ad92157936db3411e2cf7325665fc59e2d159204f9424895cfa9f33122af1
license    : GPL-3.0-or-later
component  : system.utils
summary    : A backup program for disk arrays
description: |
    Snapraid stores parity information of your data and can recover it from up to six disk failures
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
