name       : snapraid
version    : 11.2
release    : 1
source     :
    - https://github.com/amadvance/snapraid/releases/download/v11.2/snapraid-11.2.tar.gz : 735cdeb7656ac48cbb0b4a89a203dd566505071e465d5effbcc56bcb8fd3a0d7
license    : GPL-3.0-or-later
component  : system.utils
summary    : A backup program for disk arrays
description: |
    Snapraid stores parity information of your data and can recover it from up to six disk failures
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
